name = "CompressingSolvers"
uuid = "ee8cdd4e-c1c6-4e20-b2bd-c597b34c2dac"
authors = ["Florian Schaefer <flotosch@gmail.com> and contributors"]
version = "0.1.0"

[deps]
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
